FROM python:3.14-alpine AS builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /simulator

COPY uv.lock  pyproject.toml .python-version ./
COPY broker/pyproject.toml broker/
COPY common/pyproject.toml common/

RUN  --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-editable

COPY broker/  broker/
COPY common/  common/

RUN --mount=type=cache,target=/root/.cache/uv \ 
    uv sync --all-packages --no-editable 

FROM python:3.14-alpine AS runner
ENV PYTHONUNBUFFERED=1
WORKDIR /simulator

COPY --from=builder /simulator/.venv/ .venv/
ENV PATH="/simulator/.venv/bin:$PATH"
CMD ["broker"]
