[project]
name = "simulator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = ["common", "sensorAPI", "broker"]

[tool.uv.sources]
common = { workspace = true }
sensorAPI = { workspace = true }
broker = { workspace = true }

[tool.uv.workspace]
members = ["common", "sensorAPI", "broker"]
exclude = ["packages/seeds"]
