services:
#region SIMULATOR
  kafka:
    image: apache/kafka:latest
    container_name: "Kafka"
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - simulatorNET
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    profiles: [ kafka ]

  simulator:
    build:
      dockerfile: "Dockerfile"
      context: "./simulator"
    container_name: Simulator
    networks:
      - simulatorNET
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - /tmp/sim:/tmp
    
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      DB_URL: "sqlite+aiosqlite:////tmp/db.db"
    profiles: [ simulator ]
# endregion

#region BACKEND
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: "TS_DB"
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    networks:
      - backendNET
    profiles: [ backend ]

# endregion
networks:
  simulatorNET:
  backendNET: