services:
  kafka:
    image: apache/kafka:latest
    container_name: "Kafka"
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - simulatorNET
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Добавляем слушатель для внешних подключений на порт 29092
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      # Указываем, что для внешних подключений адрес — localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  sim_sensors:
    build:
      dockerfile: "Dockerfile.sensor"
      context: "./simulator"
    container_name: Sensors
    networks:
      - simulatorNET
    volumes:
      - ./simulator/db.db:/simulator/db.db

  sim_pusher:
    build:
      dockerfile: "Dockerfile.broker"
      context: "./simulator"
    container_name: Pusher
    networks:
      - simulatorNET
    depends_on:
      - sim_sensors
      - kafka
    volumes:
      - ./simulator/db.db:/simulator/db.db
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
  simulatorNET:
