[project]
name = "ingestor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Eugene", email = "evgenijgoncarevic@gmail.com" }]
requires-python = ">=3.14"
dependencies = ["aiokafka>=0.14.0", "protobuf>=7.35.1"]

[project.scripts]
ingestor = "ingestor:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
