"""init

Revision ID: 0001
Revises:
Create Date: 2026-06-20 15:15:54.096887

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensors",
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("TRAFFIC", "AIR_Q", "TEMP", name="availablesensors"),
            nullable=False,
        ),
        sa.Column("serial_number", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("serial_number"),
    )
    op.create_index(
        "idx_sensors_lat_lon", "sensors", ["lat", "lon", "type"], unique=True
    )
    op.create_table(
        "sensor_data",
        sa.Column("rowid", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("sensor_sn", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_sn"], ["sensors.serial_number"], name="fkssn", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.create_index(
        "idx_sensordata_sensor_ts", "sensor_data", ["sensor_sn", "ts"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_sensordata_sensor_ts", table_name="sensor_data")
    op.drop_table("sensor_data")
    op.drop_index("idx_sensors_lat_lon", table_name="sensors")
    op.drop_table("sensors")
    # ### end Alembic commands ###
