"""init

Revision ID: 001
Revises: 
Create Date: 2026-01-31 15:28:35.831014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('TRAFFIC', 'AIR_Q', 'TEMP', name='sensorenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_index('idx_sensor_lat_lon', 'sensor', ['lat', 'lon', 'type'], unique=True)
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('isDelivered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.sensor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_queue', 'sensor_data', ['id'], unique=False, sqlite_where=sa.text('"isDelivered" = 0'))
    op.create_index('idx_sensordata_sensor_ts', 'sensor_data', ['sensor_id', 'ts'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sensordata_sensor_ts', table_name='sensor_data')
    op.drop_index('idx_delivery_queue', table_name='sensor_data', sqlite_where=sa.text('"isDelivered" = 0'))
    op.drop_table('sensor_data')
    op.drop_index('idx_sensor_lat_lon', table_name='sensor')
    op.drop_table('sensor')
    # ### end Alembic commands ###
