[project]
name = "sensorapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Eugene", email = "evgenijgoncarevic@gmail.com" }]
requires-python = ">=3.14"
dependencies = ["aiosqlite>=0.22.0", "sqlalchemy>=2.0.45", "common"]

[tool.uv.sources]
common = { workspace = true }

[project.scripts]
sensor = "sensorapi:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
