# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_data.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "sensor_data.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11sensor_data.proto\x12\ttelemetry"+\n\x0eTelemetryPoint\x12\n\n\x02ts\x18\x01 \x01(\x02\x12\r\n\x05value\x18\x02 \x01(\x01"u\n\x0f\x44\x65viceDataBatch\x12\x11\n\tsensor_sn\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x02\x12\x0b\n\x03lon\x18\x04 \x01(\x02\x12\'\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x19.telemetry.TelemetryPoint"C\n\x14\x42ulkIngestionPayload\x12+\n\x07\x62\x61tches\x18\x01 \x03(\x0b\x32\x1a.telemetry.DeviceDataBatchb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sensor_data_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TELEMETRYPOINT"]._serialized_start = 32
    _globals["_TELEMETRYPOINT"]._serialized_end = 75
    _globals["_DEVICEDATABATCH"]._serialized_start = 77
    _globals["_DEVICEDATABATCH"]._serialized_end = 194
    _globals["_BULKINGESTIONPAYLOAD"]._serialized_start = 196
    _globals["_BULKINGESTIONPAYLOAD"]._serialized_end = 263
# @@protoc_insertion_point(module_scope)
