"""init

Revision ID: 0001
Revises: 
Create Date: 2026-02-09 19:41:24.117455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()





def upgrade_timescale() -> None:
    """Upgrade timescale schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_timescale() -> None:
    """Downgrade timescale schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###


def upgrade_sqlite() -> None:
    """Upgrade sqlite schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_buffer',
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('sensor_id'),
    sa.UniqueConstraint('ts', 'value', 'sensor_id', name='ts_value_sensor_id', sqlite_on_conflict='IGNORE')
    )
    # ### end Alembic commands ###


def downgrade_sqlite() -> None:
    """Downgrade sqlite schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge_buffer')
    # ### end Alembic commands ###

