"""init

Revision ID: 0001
Revises:
Create Date: 2026-03-16 20:25:27.889011

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(engine_name: str = "timescale") -> None:
    """Upgrade schema."""
    globals()[f"upgrade_{engine_name}"]()


def downgrade(engine_name: str = "timescale") -> None:
    """Downgrade schema."""
    globals()[f"downgrade_{engine_name}"]()


def upgrade_timescale() -> None:
    """Upgrade timescale schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(length=32), nullable=False),
        sa.Column("password", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "map_points",
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("title", sa.VARCHAR(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["admins.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "sensors",
        sa.Column(
            "type",
            sa.Enum("AIR", "TEMPERATURE", "TRAFFIC", name="sensortype"),
            nullable=False,
        ),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("serial_number", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("sensor_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["admins.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("sensor_id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_table(
        "bound_sensors",
        sa.Column("map_point_id", sa.UUID(), nullable=False),
        sa.Column("sensor_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["map_point_id"],
            ["map_points.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.sensor_id"],
        ),
        sa.PrimaryKeyConstraint(
            "map_point_id", "sensor_id", name="PK_map_point_id_sensor_id"
        ),
    )
    op.create_table(
        "sensor_hyper_data",
        sa.Column("sensor_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("ts", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.sensor_id"],
        ),
        sa.PrimaryKeyConstraint("ts", "sensor_id", name="PK_ts_sensor_id"),
    )
    op.execute(
        "SELECT create_hypertable('sensor_hyper_data', 'ts', if_not_exists => TRUE);"
    )
    # ### end Alembic commands ###


def downgrade_timescale() -> None:
    """Downgrade timescale schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensor_hyper_data")
    op.drop_table("bound_sensors")
    op.drop_table("sensors")
    op.drop_table("map_points")
    op.drop_table("admins")
    # ### end Alembic commands ###


def upgrade_sqlite() -> None:
    """Upgrade sqlite schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edge_buffer",
        sa.Column("rowid", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("sensor_sn", sa.UUID(), nullable=False),
        sa.Column("is_pushed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("rowid"),
        sa.UniqueConstraint(
            "ts",
            "value",
            "sensor_sn",
            name="ts_value_sensor_sn",
            sqlite_on_conflict="IGNORE",
        ),
    )
    # ### end Alembic commands ###


def downgrade_sqlite() -> None:
    """Downgrade sqlite schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("edge_buffer")
    # ### end Alembic commands ###
