"""sensors_coordinates

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-31 17:25:39.077676

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("sensor_hyper_data_ts_idx"), table_name="sensor_hyper_data")
    op.add_column(
        "sensors",
        sa.Column(
            "coordinates",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "idx_sensors_coordinates",
        "sensors",
        ["coordinates"],
        unique=False,
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.drop_column("sensors", "lat")
    op.drop_column("sensors", "lon")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sensors",
        sa.Column(
            "lon",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "sensors",
        sa.Column(
            "lat",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(
        "idx_sensors_coordinates", table_name="sensors", postgresql_using="gist"
    )
    op.drop_column("sensors", "coordinates")
    op.create_index(
        op.f("sensor_hyper_data_ts_idx"),
        "sensor_hyper_data",
        [sa.literal_column("ts DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
