"""schema_upgrade

Revision ID: 0002
Revises: 0001
Create Date: 2026-02-17 20:33:10.859007

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()


def upgrade_timescale() -> None:
    """Upgrade timescale schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_points",
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("title", sa.VARCHAR(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["admins.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "sensors",
        sa.Column(
            "type",
            sa.Enum("AIR", "TEMPERATURE", "TRAFFIC", name="sensortype"),
            nullable=False,
        ),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("serial_number", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("sensor_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["admins.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("sensor_id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_table(
        "bound_sensors",
        sa.Column("map_point_id", sa.UUID(), nullable=False),
        sa.Column("sensor_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["map_point_id"],
            ["map_points.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.sensor_id"],
        ),
        sa.PrimaryKeyConstraint(
            "map_point_id", "sensor_id", name="PK_map_point_id_sensor_id"
        ),
    )
    op.create_table(
        "sensor_hyper_data",
        sa.Column("sensor_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("ts", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.sensor_id"],
        ),
        sa.PrimaryKeyConstraint("ts", "sensor_id", name="PK_ts_sensor_id"),
    )
    op.add_column("admins", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, "admins", ["username"])
    # ### end Alembic commands ###


def downgrade_timescale() -> None:
    """Downgrade timescale schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "admins", type_="unique")
    op.drop_column("admins", "is_deleted")
    op.drop_table("sensor_hyper_data")
    op.drop_table("bound_sensors")
    op.drop_table("sensors")
    op.drop_table("map_points")
    # ### end Alembic commands ###


def upgrade_sqlite() -> None:
    """
    Upgrade sqlite schema using batch mode.
    All table modifications must stay inside the batch context for SQLite support.
    """
    with op.batch_alter_table("edge_buffer", schema=None) as bop:
        # Alter columns
        bop.alter_column(
            "value", existing_type=sa.TEXT(), type_=sa.Float(), existing_nullable=False
        )
        bop.alter_column(
            "sensor_sn",
            existing_type=sa.NUMERIC(),
            type_=sa.UUID(),
            existing_nullable=False,
        )

        # Constraints and Drops (MUST be inside batch for SQLite)
        bop.drop_constraint("ts_value_sensor_id", type_="unique")
        bop.create_unique_constraint("ts_value_sensor_sn", ["ts", "value", "sensor_sn"])
        bop.drop_column("sensor_id")


def downgrade_sqlite() -> None:
    """
    Downgrade sqlite schema using batch mode.
    """
    with op.batch_alter_table("edge_buffer", schema=None) as bop:
        # Revert additions and constraints
        bop.add_column(sa.Column("sensor_id", sa.NUMERIC(), nullable=False))
        bop.drop_constraint("ts_value_sensor_sn", type_="unique")
        bop.create_unique_constraint("ts_value_sensor_id", ["ts", "value", "sensor_id"])

        # Revert types
        bop.alter_column(
            "sensor_sn",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
        bop.alter_column(
            "value",
            existing_type=sa.Float(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
