name: Python application CI

on:
  push:
    branches: [main, cicd-test, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        components: [simulator, backend]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        working-directory: ${{matrix.components}}
        run: uv sync --all-packages

      - name: Run tests
        working-directory: ${{matrix.components}}
        run: uv run pytest
